---
pool:
  name: 'mvn-cicd'
  VmImage: 'ubuntu-latest'
trigger:
  - main
steps:
  - task: Maven@3
    inputs:
      mavenPOMFile: 'pom.xml'
      goals: 'package'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      testRunTitle: 'unittests'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'